import sharp from "sharp";
import { IssueServiceError } from "../errors";
import {
  ATTACHMENT_MAX_DIMENSION,
  ATTACHMENT_MAX_PIXELS,
  ATTACHMENT_THUMBNAIL_MAX_DIMENSION,
  type AttachmentContentType,
} from "./limits";

export interface NormalizedImage {
  bytes: Buffer;
  contentType: AttachmentContentType;
  width: number;
  height: number;
}

export interface ProcessedAttachmentImage {
  original: NormalizedImage;
  thumbnail: NormalizedImage;
}

export interface ImageProcessingLimits {
  maxPixels: number;
  maxDimension: number;
  thumbnailMaxDimension: number;
  /** Bounded decode+encode wall time. */
  timeoutMs: number;
}

export const DEFAULT_IMAGE_PROCESSING_LIMITS: ImageProcessingLimits = {
  maxPixels: ATTACHMENT_MAX_PIXELS,
  maxDimension: ATTACHMENT_MAX_DIMENSION,
  thumbnailMaxDimension: ATTACHMENT_THUMBNAIL_MAX_DIMENSION,
  timeoutMs: 15_000,
};

function invalidImage(reason: string): IssueServiceError {
  return new IssueServiceError("invalid_attachment", "The image could not be accepted.", {
    details: [{ field: "file", reason }],
  });
}

/**
 * Cheap magic-byte sniff, checked before the decoder runs and cross-checked
 * against the decoded format: SVG, GIF, HTML, PDF, HEIC, polyglots, and
 * arbitrary files never reach the raster pipeline.
 */
function sniffFormat(bytes: Uint8Array): "png" | "jpeg" | "webp" | null {
  if (bytes.length >= 4 && bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47) {
    return "png";
  }
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return "jpeg";
  }
  if (
    bytes.length >= 12
    && bytes[0] === 0x52 && bytes[1] === 0x49 && bytes[2] === 0x46 && bytes[3] === 0x46
    && bytes[8] === 0x57 && bytes[9] === 0x45 && bytes[10] === 0x42 && bytes[11] === 0x50
  ) {
    return "webp";
  }
  return null;
}

async function withTimeout<T>(work: Promise<T>, timeoutMs: number): Promise<T> {
  const timeout = Symbol("timeout");
  let timer: NodeJS.Timeout | undefined;
  const settled = work.then(
    (value) => ({ value }),
    (error: unknown) => ({ error }),
  );
  try {
    const result = await Promise.race([
      settled,
      new Promise<typeof timeout>((resolve) => {
        timer = setTimeout(() => {
          resolve(timeout);
        }, timeoutMs);
        timer.unref();
      }),
    ]);
    if (result === timeout) {
      await settled;
      throw invalidImage("processing timed out");
    }
    if ("error" in result) {
      throw result.error;
    }
    return result.value;
  } finally {
    if (timer !== undefined) {
      clearTimeout(timer);
    }
  }
}

/**
 * Decodes untrusted raster input under pixel/dimension/time bounds and
 * re-encodes it: auto-orientation applied, EXIF/GPS and all other metadata
 * stripped (sharp only carries metadata when asked), animation rejected, and
 * the format pinned to the sniffed type. The thumbnail is a bounded WebP.
 * Only server-generated bytes from this function are ever stored or served.
 */
export async function processAttachmentImage(
  input: Buffer,
  limits: ImageProcessingLimits = DEFAULT_IMAGE_PROCESSING_LIMITS,
): Promise<ProcessedAttachmentImage> {
  const sniffed = sniffFormat(input);
  if (sniffed === null) {
    throw invalidImage("unsupported image type");
  }
  try {
    return await withTimeout(process(input, sniffed, limits), limits.timeoutMs);
  } catch (error) {
    if (error instanceof IssueServiceError) {
      throw error;
    }
    throw invalidImage("not a valid image");
  }
}

async function process(
  input: Buffer,
  sniffed: "png" | "jpeg" | "webp",
  limits: ImageProcessingLimits,
): Promise<ProcessedAttachmentImage> {
  // limitInputPixels makes the decoder itself refuse pixel bombs instead of
  // allocating for them; `failOn: "error"` rejects truncated/corrupt streams.
  const base = sharp(input, {
    limitInputPixels: limits.maxPixels,
    animated: false,
    failOn: "error",
  })
    .timeout({ seconds: Math.max(1, Math.ceil(limits.timeoutMs / 1000)) })
    .rotate();
  const metadata = await base.metadata();
  if (metadata.format !== sniffed) {
    throw invalidImage("image content does not match its type");
  }
  if ((metadata.pages ?? 1) > 1) {
    throw invalidImage("animated images are not supported");
  }
  const width = metadata.width ?? 0;
  const height = metadata.height ?? 0;
  const orientedWidth = (metadata.orientation ?? 1) >= 5 ? height : width;
  const orientedHeight = (metadata.orientation ?? 1) >= 5 ? width : height;
  if (
    orientedWidth < 1
    || orientedHeight < 1
    || orientedWidth > limits.maxDimension
    || orientedHeight > limits.maxDimension
    || orientedWidth * orientedHeight > limits.maxPixels
  ) {
    throw invalidImage("image dimensions are too large");
  }

  const contentType: AttachmentContentType =
    sniffed === "png" ? "image/png" : sniffed === "jpeg" ? "image/jpeg" : "image/webp";
  const reencode =
    sniffed === "png"
      ? base.clone().png({ compressionLevel: 9 })
      : sniffed === "jpeg"
        ? base.clone().jpeg({ quality: 90, mozjpeg: true })
        : base.clone().webp({ quality: 90 });
  const originalBytes = await reencode.toBuffer({ resolveWithObject: true });
  if (
    originalBytes.info.width !== orientedWidth
    || originalBytes.info.height !== orientedHeight
  ) {
    throw invalidImage("image dimensions are too large");
  }

  const thumbnailBytes = await base
    .clone()
    .resize({
      width: limits.thumbnailMaxDimension,
      height: limits.thumbnailMaxDimension,
      fit: "inside",
      withoutEnlargement: true,
    })
    .webp({ quality: 85 })
    .toBuffer({ resolveWithObject: true });

  return {
    original: {
      bytes: originalBytes.data,
      contentType,
      width: originalBytes.info.width,
      height: originalBytes.info.height,
    },
    thumbnail: {
      bytes: thumbnailBytes.data,
      contentType: "image/webp",
      width: thumbnailBytes.info.width,
      height: thumbnailBytes.info.height,
    },
  };
}

/** Tiny bounded concurrency pool so decode spikes cannot stall Fastify. */
export class ImageProcessingPool {
  private active = 0;
  private readonly waiting: Array<() => void> = [];

  constructor(private readonly maxConcurrent: number) {}

  async run<T>(work: () => Promise<T>): Promise<T> {
    if (this.active >= this.maxConcurrent) {
      await new Promise<void>((resolve) => {
        this.waiting.push(resolve);
      });
    }
    this.active += 1;
    try {
      return await work();
    } finally {
      this.active -= 1;
      const next = this.waiting.shift();
      if (next !== undefined) {
        next();
      }
    }
  }
}
